# netlify.toml

[build]
  command = "chmod +x configure.sh && ./configure.sh"
  publish = "book"

[context.production]
  command = "chmod +x configure.sh && ./configure.sh"
  publish = "book"

[context.cache]
  key = "v1-cargo-deps"
  paths = [
    "$HOME/.cargo/registry",
    "$HOME/.cargo/git",
    "$HOME/.rustup",
    "target/",
  ]

[[plugins]]
package = "netlify-plugin-rust-cache"

[plugins.inputs]
paths = ["target/", "Cargo.lock"]
