[build]
  command = "npm install && chmod +x configure.sh && ./configure.sh"
  publish = "book"

[build.environment]
  CARGO_HOME = "$HOME/.cargo"
  RUSTUP_HOME = "$HOME/.rustup"
  RUSTUP_DIST_SERVER = "https://rsproxy.cn"
  RUSTUP_UPDATE_ROOT = "https://rsproxy.cn/rustup"

[context.cache]
  key = "v1-cargo-deps"
  paths = [
    "/opt/buildhome/.cargo/registry",
    "/opt/buildhome/.cargo/git",
    "/opt/buildhome/.rustup",
    "/opt/buildhome/.cargo/bin",  # 确保缓存 ~/.cargo/bin
    "target/",
  ]

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
    paths = [
      "$HOME/.cargo/registry",
      "$HOME/.cargo/git",
      "$HOME/.rustup",
      "target/",
    ]