[build]
  base = "./" # Trick to disable dependencies installation
  command = "chmod +x ./scripts/netlify/build.sh && ./scripts/netlify/build.sh && python updateidx.py && python -m mkdocs build -v"
  publish = "site"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/ui/*"
  to = "/.netlify/functions/comment/ui/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/comment/api/:splat"
  status = 200