[package]
name = "mdbook-mathjax-preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4.44"
regex = "1.10"
fancy-regex = "0.14.0"
once_cell = "1.19"
pulldown-cmark = "0.9"
pulldown-cmark-to-cmark = "10.0"
serde_json = "1.0"